<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_permanentAddress</name>
   <tag></tag>
   <elementGuidId>89287336-f955-49da-8880-fc93c88aa754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permanentAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'permanentAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permanentAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e125c777-63dc-4c31-a478-ef4eb82d5435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3a21adfc-d52e-4f29-b1de-fc379245956e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>37c01148-ea0d-4a04-a0ea-690bc4d6b267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanentAddress</value>
      <webElementGuid>e71ec6d4-ac6f-4a87-bbd8-504bd46fc2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b87cac8e-f239-4b9c-97e0-d626fb35998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-062285153cb93eac3553058c2f8365a0</value>
      <webElementGuid>42cde96f-4334-4d60-bfbe-3ab48e8fc12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'permanentAddress']</value>
      <webElementGuid>315d9668-60ca-42b3-a5e1-85da307c30f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'permanentAddress']</value>
      <webElementGuid>09541f1d-ab3d-4419-a0c3-b427710f3d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'permanentAddress']</value>
      <webElementGuid>64c9be72-3041-482b-86c2-4987d4b1f513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
